[build-system]
requires = ["pyecore"]
build-backend = "pyecore"

[project]
name = "Interface-KB"
authors = [{name = "Bert Van Acker", email = "bert.vanacker@uantwerpen.be"}]
dynamic = ["version", "description"]
